"""Initial schema.

Applies the canonical DDL from ``db/schema.sql`` (extensions, enum types, all
tables, indexes and the audit / updated_at triggers). Keeping a single SQL file
as the source of truth avoids drift between the documented schema and the
database. Subsequent changes use ordinary autogenerated Alembic revisions.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-05-30
"""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path

from alembic import op

revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Candidate locations for the canonical DDL (repo layout and Docker image).
_CANDIDATES = [
    Path(__file__).resolve().parents[3] / "db" / "schema.sql",  # monorepo root/db
    Path("/app/db/schema.sql"),                                  # Docker image
    Path(__file__).resolve().parents[2] / "db" / "schema.sql",   # backend/db (fallback)
]

# Drop order is the reverse of creation; CASCADE handles dependencies.
_ENUM_TYPES = [
    "asset_class", "transaction_type", "transaction_source", "import_status",
    "import_row_status", "recommendation", "valuation_verdict", "valuation_method",
    "alert_type", "alert_channel", "notification_status", "fire_type", "ai_provider",
    "report_type", "report_format", "report_status", "dividend_kind", "cost_basis_method",
]

_TABLES = [
    "reports", "tax_summaries", "notifications", "alerts", "watchlist_items", "watchlists",
    "scenarios", "fire_plans", "ai_analyses", "valuations", "asset_scores", "dividends",
    "portfolio_snapshots", "positions", "import_rows", "transactions", "import_batches",
    "portfolios", "brokers", "dividend_schedule", "fundamentals", "fx_rates",
    "price_history", "assets", "audit_log", "user_settings", "devices", "users",
]


def _read_schema_sql() -> str:
    for candidate in _CANDIDATES:
        if candidate.exists():
            return candidate.read_text(encoding="utf-8")
    raise FileNotFoundError(
        "db/schema.sql not found. Ensure the canonical schema file is available "
        f"in one of: {', '.join(str(c) for c in _CANDIDATES)}"
    )


def _split_statements(sql: str) -> list[str]:
    """Split SQL into individual statements, respecting dollar-quoted blocks.

    Needed because async drivers (asyncpg) reject multi-statement strings, and
    the schema contains PL/pgSQL functions whose bodies use ``$$ ... $$`` and
    therefore contain semicolons that must not split statements.
    """
    statements: list[str] = []
    buf: list[str] = []
    dollar_tag: str | None = None
    i = 0
    n = len(sql)
    while i < n:
        ch = sql[i]
        # Line comment outside a dollar-quote: skip to end of line.
        if dollar_tag is None and ch == "-" and i + 1 < n and sql[i + 1] == "-":
            eol = sql.find("\n", i)
            if eol == -1:
                break
            buf.append(sql[i:eol])
            i = eol
            continue
        # Dollar-quote delimiter (e.g. $$ or $tag$).
        if ch == "$":
            end = sql.find("$", i + 1)
            if end != -1:
                tag = sql[i : end + 1]
                if dollar_tag is None:
                    dollar_tag = tag
                elif dollar_tag == tag:
                    dollar_tag = None
                buf.append(tag)
                i = end + 1
                continue
        # Statement terminator outside a dollar-quote.
        if ch == ";" and dollar_tag is None:
            statement = "".join(buf).strip()
            if statement:
                statements.append(statement)
            buf = []
            i += 1
            continue
        buf.append(ch)
        i += 1
    tail = "".join(buf).strip()
    if tail:
        statements.append(tail)
    return statements


def upgrade() -> None:
    for statement in _split_statements(_read_schema_sql()):
        op.execute(statement)


def downgrade() -> None:
    for table in _TABLES:
        op.execute(f"DROP TABLE IF EXISTS {table} CASCADE")
    for enum in _ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {enum} CASCADE")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at() CASCADE")
    op.execute("DROP FUNCTION IF EXISTS audit_trigger() CASCADE")
